apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - image: flauberjp/udagram-reverseproxy
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          imagePullPolicy: Always
          name: reverseproxy
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
